language: objective-c
osx_image: xcode9.2
xcode_workspace: Doughnut.xcworkspace
xcode_scheme: DoughnutTests



script:
- xcodebuild -workspace Doughnut.xcworkspace -scheme Doughnut build-for-testing -quiet
- TEST=true xctool -workspace Doughnut.xcworkspace -scheme Doughnut run-tests -only DoughnutTests
