language: node_js
node_js:
- '5'

sudo: false

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - xvfb

before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
  - npm run rebuild